name: Secrets and variables

on:
  workflow_dispatch:

jobs:
  staging-environment:
    runs-on: ubuntu-24.04
    environment: staging
    env:
      EXAMPLE_REPOSITORY_SECRET: ${{ secrets.EXAMPLE_REPOSITORY }}
    steps:
      - name: Inspect values inside jobs
        run: |
          echo "Repo secret (masked): $EXAMPLE_REPOSITORY_SECRET"