name: Environment Variables example

on:
  workflow_dispatch:

env:
  WORKFLOW_VAR: I_AM_A_WORKFLOW_ENV_VAR

jobs:
  job-1:
    runs-on: ubuntu-24.04
    env:
      JOB_VAR: I_AM_A_JOB_ENV_VAR
    steps:
      - name: Inspect scope job 1 step 1
        env: 
          STEP_VAR: I_AM_A_STEP_ENV_VAR
        run: |
          echo "WORKFLOW_VAR: $WORKFLOW_VAR"  # visible
          echo "JOB_VAR: $JOB_VAR"            # visible
          echo "STEP_VAR: $STEP_VAR"          # visible only in this step
      - name: Inspect scope job 1 step 2
        run: |
          echo "WORKFLOW_VAR: $WORKFLOW_VAR"  # visible
          echo "JOB_VAR: $JOB_VAR"            # visible
          echo "STEP_VAR: $STEP_VAR"          # NOT visible in this step

  job-2:
    runs-on: ubuntu-24.04
    steps:
      - name: Inspect scope job 2 step 2
        run: |
          echo "WORKFLOW_VAR: $WORKFLOW_VAR"  # visible
          echo "JOB_VAR: $JOB_VAR"            # NOT visible in this job
          echo "STEP_VAR: $STEP_VAR"          # NOT visible in this step